base_url: "http://api.openweathermap.org/data/2.5/weather"

cities:
  - name: "Moscow"
    id: 524901
  - name: "Grodno"
    id: 627907
  - name: "Yuzhno-Sakhalinsk"
    id: 2119441
  - name: "Orekhovo-Borisovo Yuzhnoye"
    id: 572449


temperature_thresholds:
  high: 10
  low: 0


data_storage:
  netcdf_path: "data/weather_data.nc"

